/* eslint-disable */
// WARNING: This file is automatically generated by AWS Amplify.
// Do not edit this file directly; edit the backend configuration and regenerate it.

import { Auth } from 'aws-amplify';

const awsmobile = {
    aws_project_region: 'ap-southeast-2',
    aws_cognito_region: 'ap-southeast-2',
    aws_user_pools_id: 'REPLACE_WITH_USER_POOL_ID',
    aws_user_pools_web_client_id: 'REPLACE_WITH_WEB_CLIENT_ID',
    oauth: {},
    aws_cloud_logic_custom: [
        {
            name: 'restapi',
            endpoint: 'REPLACE_WITH_API_ENDPOINT',
            region: 'ap-southeast-2',
            custom_header: async () => {
                try {
                    const session = await Auth.currentSession();
                    return { Authorization: `Bearer ${session.getIdToken().getJwtToken()}` };
                } catch (e) {
                    return {};
                }
            }
        }
    ]
};

export default awsmobile;
